// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJzdGGxiNKheB2RkWUXcZnDRWlgo2rQM',
    appId: '1:650160732588:web:3079571ddc466d86826209',
    messagingSenderId: '650160732588',
    projectId: 'mymusic-8500',
    authDomain: 'mymusic-8500.firebaseapp.com',
    storageBucket: 'mymusic-8500.appspot.com',
    measurementId: 'G-80LXWMP43H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqGci47UnlsgD0VeUck4W5JHX8MNJss74',
    appId: '1:650160732588:android:27b51eb3034be6d4826209',
    messagingSenderId: '650160732588',
    projectId: 'mymusic-8500',
    storageBucket: 'mymusic-8500.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJzdGGxiNKheB2RkWUXcZnDRWlgo2rQM',
    appId: '1:650160732588:web:37b6794e9d182525826209',
    messagingSenderId: '650160732588',
    projectId: 'mymusic-8500',
    authDomain: 'mymusic-8500.firebaseapp.com',
    storageBucket: 'mymusic-8500.appspot.com',
    measurementId: 'G-CCVE9Q1425',
  );
}
